version: "3.7" 
services:
  # nginx:
  #   image: nginx:1.19.6
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - "../coloniaonline.com.br:/var/www/html/public"
  #     - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
  #   links:
  #     - php
  #     - mysql
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - "./webserver/ports.conf:/etc/apache2/ports.conf"
      - "../coloniaonline.com.br:/var/www/html"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
      # - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
      - "./backups:/root/backups"
    environment:
      MYSQL_DATABASE: 'colonialocal'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345'
volumes:
  mysql:
